import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  // HOME PAGE ONLY: scan only files that render on "/" (see docs/home-page-css-inventory.md).
  // Other routes (e.g. /contact-us, /admin, (pages)) will NOT get Tailwind styles. Add their paths here if needed.
  content: [
    "./app/page.tsx",
    "./app/layout.tsx",
    "./app/MainLayout.tsx",
    "./app/(pages)/HomeDataProvider.tsx",
    "./app/(pages)/take-my-class/page.tsx",
    "./app/(pages)/take-my-class-2/page.tsx",
    "./app/(pages)/take-my-exam/page.tsx",
    "./app/(pages)/take-my-proctored-exam/page.tsx",
    "./app/(pages)/tools/**/*.tsx",
    "./app/(pages)/plagiarism-free-process/page.tsx",
    "./app/(pages)/write-my-paper/page.tsx",
    "./app/(pages)/plagiarism-free-process/page.tsx",
    "./app/(pages)/on-time-delivery-guarantee/page.tsx",
    "./app/(pages)/a-or-b-grade-guarantee/page.tsx",
    "./app/(pages)/us-based-phd-experts/page.tsx",
    "./app/(pages)/success-stories-and-reviews/page.tsx",
    "./app/(pages)/terms-and-conditions/page.tsx",
    "./app/(pages)/privacy-policy/page.tsx",
    "./app/(pages)/contact-us/page.tsx",
    "./app/(pages)/about-us/page.tsx",
    "./app/(pages)/faq/page.tsx",
    "./app/(pages)/essay-writing/page.tsx",
    "./app/(pages)/essay-writing/[subject]/page.tsx",
    "./app/(pages)/exams/page.tsx",
    "./app/(pages)/homework/page.tsx",
    "./app/(pages)/online-class/page.tsx",
    "./app/(pages)/online-class-2/page.tsx",
    "./app/(pages)/AiTools/**/*.tsx",
    "./app/context/auth/AuthProvider.tsx",
    "./app/components/AcademicPartner/**/*.tsx",
    "./app/components/AiLandingPage/**/*.tsx",
    "./app/components/AiTools/**/*.tsx",
    "./app/components/OtherLandingPages/**/*.tsx",
    "./app/components/LandingPage/**/*.tsx",
    "./app/components/Footer/**/*.tsx",
    "./app/components/tools/**/*.tsx",
    "./app/components/Footer/CopyRight.tsx",
    "./app/components/WhatsApp/WhatsApp.tsx",
    "./app/components/CookieConsent.tsx",
    "./app/components/reusable/HeroWhySliderCard.tsx",
    "./app/components/Auth/**/*.tsx",
    
    "./app/(admin)/**/*.tsx",
    "./public/**/*.html",
  ],
  // Only safelist classes that are ACTUALLY dynamically generated
  safelist: [
    'animate-pulse',
    'bg-gray-100',
  ],
  // Blocklist unused Tailwind utilities to reduce CSS bundle
  blocklist: [
    // Remove unused dark mode variants if not using dark mode on landing page
    'dark',
  ],
  theme: {
    screens: {
      sm: "576px",
      md: "768px",
      mid: "827px",
      lg: "992px",
      xl: "1200px",
      "2xl": "1400px",
    },
    extend: {
      // Container: center by default and optional padding (so "container" works without mx-auto)
      container: {
        center: true,
        padding: {
          DEFAULT: "1rem",
          sm: "1.5rem",
          md: "2rem",
          lg: "2rem",
          xl: "2rem",
          "2xl": "2rem",
        },
      },
      // Override default font family to prevent Inter loading
      fontFamily: {
        sans: ['var(--font-poppins)', 'system-ui', '-apple-system', 'Segoe UI', 'Arial', 'sans-serif'],
        poppins: ['var(--font-poppins)', 'system-ui', '-apple-system', 'Segoe UI', 'Arial', 'sans-serif'],
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
        sample: "url('/Image/sampleBg.webp')",
        heroImage: "url('/Image/bgHeroBoyGirl.webp')",
      },
      colors: {
        primary: {
          100: "#F7F7FD",
          200: "#ECECFB",
          300: "#D1D1F7",
          400: "#565add",
          500: "#2B1C50",
          600: "#212529",
        },
        secondary: {
          200: "#F2E0C7",
          400: "#f97316",
          500: "#ff641a",
        },
      },
    },
  },
  // Only disable plugins with ZERO usage in app/ (keeps bundle small, UI intact)
  corePlugins: {
    preflight: true,
    container: true,
    display: true,
    position: true,
    inset: true,
    zIndex: true,
    overflow: true,
    margin: true,
    padding: true,
    width: true,
    height: true,
    minWidth: true,
    minHeight: true,
    maxWidth: true,
    maxHeight: true,
    flex: true,
    flexDirection: true,
    alignItems: true,
    justifyContent: true,
    gap: true,
    gridTemplateColumns: true,
    fontFamily: true,
    fontSize: true,
    fontWeight: true,
    lineHeight: true,
    textAlign: true,
    textColor: true,
    letterSpacing: true,
    textTransform: true,
    backgroundColor: true,
    borderWidth: true,
    borderColor: true,
    borderRadius: true,
    boxShadow: true,
    opacity: true,
    cursor: true,
    pointerEvents: true,
    userSelect: false,
    aspectRatio: false,
    filter: false,
    backdropBlur: true,
    blur: true,
    brightness: false,
    contrast: false,
    grayscale: true,
    hueRotate: false,
    invert: true,
    saturate: false,
    sepia: false,
    mixBlendMode: false,
    isolation: false,
    scrollSnapAlign: true,
    scrollSnapStop: false,
    scrollSnapType: true,
    touchAction: false,
    willChange: false,
  },
  plugins: [require("tailwind-scrollbar-hide")],
};
export default config;
