import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{tsx,jsx,ts,js}",
    "./app/components/**/*.{tsx,jsx,ts,js}",
  ],
  safelist: ['animate-pulse'],
  blocklist: ['dark'],
  theme: {
    screens: {
      sm: "576px",
      md: "768px",
      mid: "827px",
      lg: "992px",
      xl: "1200px",
      "2xl": "1400px",
    },
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      white: '#ffffff',
      black: '#000000',
      primary: {
        100: "#F7F7FD",
        200: "#ECECFB",
        300: "#D1D1F7",
        400: "#565add",
        500: "#2B1C50",
        600: "#212529"
      },
      secondary: {
        200: "#F2E0C7",
        400: "#f97316",
        500: "#ff641a"
      },
      gray: {
        50: '#f9fafb',
        100: '#f3f4f6',
        200: '#e5e7eb',
        300: '#d1d5db',
        400: '#9ca3af',
        500: '#6b7280',
        600: '#4b5563',
        700: '#374151',
        800: '#1f2937',
        900: '#111827',
      },
    },
    extend: {
      container: {
        center: true,
        padding: {
          DEFAULT: "1rem",
          sm: "1.5rem",
          md: "2rem",
          lg: "2rem",
          xl: "2rem",
          "2xl": "2rem",
        },
      },
      fontFamily: {
        poppins: ['var(--font-poppins)', 'system-ui', '-apple-system', 'Segoe UI', 'Arial', 'sans-serif'],
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic": "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
        sample: "url('/Image/sampleBg.webp')",
        heroImage: "url('/Image/bgHeroBoyGirl.webp')",
      },
    },
  },
  corePlugins: {
    preflight: true,
    container: true,
    display: true,
    position: true,
    inset: true,
    zIndex: true,
    overflow: true,
    margin: true,
    padding: true,
    width: true,
    height: true,
    minWidth: true,
    minHeight: true,
    maxWidth: true,
    maxHeight: true,
    flex: true,
    flexDirection: true,
    alignItems: true,
    justifyContent: true,
    gap: true,
    gridTemplateColumns: true,
    gridTemplateRows: false,
    gridColumn: true,
    gridRow: true,
    fontFamily: true,
    fontSize: true,
    fontWeight: true,
    lineHeight: true,
    textAlign: true,
    textColor: true,
    letterSpacing: true,
    textTransform: true,
    backgroundColor: true,
    borderWidth: true,
    borderColor: true,
    borderRadius: true,
    boxShadow: true,
    opacity: true,
    cursor: true,
    pointerEvents: true,
    userSelect: false,
    aspectRatio: false,
    filter: false,
    backdropBlur: true,
    blur: true,
    brightness: false,
    contrast: false,
    grayscale: false,
    hueRotate: false,
    invert: false,
    saturate: false,
    sepia: false,
    mixBlendMode: false,
    isolation: false,
    scrollSnapAlign: false,
    scrollSnapStop: false,
    scrollSnapType: false,
    touchAction: false,
    willChange: false,
    fontVariantNumeric: false,
    fontSmoothing: false,
    fontStyle: false,
    textDecoration: true,
    textDecorationColor: false,
    textDecorationStyle: false,
    textDecorationThickness: false,
    textUnderlineOffset: false,
    verticalAlign: false,
    whitespace: true,
    wordBreak: false,
    backgroundAttachment: false,
    backgroundClip: false,
    backgroundOrigin: false,
    backgroundPosition: false,
    backgroundRepeat: false,
    backgroundSize: false,
    borderCollapse: false,
    borderStyle: true,
    outlineStyle: false,
    outlineWidth: false,
    outlineOffset: false,
    outlineColor: false,
    ringWidth: false,
    ringColor: false,
    ringOffsetWidth: false,
    ringOffsetColor: false,
    stroke: false,
    strokeWidth: false,
    fill: false,
    tableLayout: false,
    appearance: false,
    float: false,
    clear: false,
    listStyleType: true,
    listStylePosition: false,
    resize: false,
    transform: true,
    skew: false,
    scale: true,
    rotate: true,
    translate: true,
    backgroundOpacity: false,
    textOpacity: false,
    borderOpacity: false,
    divideOpacity: false,
    placeholderOpacity: false,
    ringOpacity: false,
  },
  plugins: [require("tailwind-scrollbar-hide")],
};
export default config;
