"use client";
import { FC, ReactNode, useState, useCallback, useEffect } from "react"; // Added useEffect
import dynamic from "next/dynamic";
import type { Metadata } from "next";
import { usePathname } from "next/navigation";

// Lazy load auth provider
const AuthProvider = dynamic(() => import("./context/auth/AuthProvider"), {
    ssr: false,
});

import AppNav from "./components/LandingPage/Header";
import Footer from "./components/Footer/Footer";

const ExitPopUp = dynamic(() => import("./components/PopUpModal/ExitPopup"), {
    ssr: false,
});

const CookieBanner = dynamic(() => import("./components/CookieConsent"), {
    ssr: false,
});

const WhatsApp = dynamic(() => import("./components/WhatsApp/WhatsApp"), {
    ssr: false,
});



export const metadata: Metadata = {
    title: "ScholarlyHelp",
    description: "Generated by create next app",
};

interface MainLayoutProps {
    children: ReactNode;
}

const MainLayout: FC<MainLayoutProps> = ({ children }) => {
    const pathname = usePathname();

    // Routes where header and footer should be hidden
    const hideHeaderFooterRoutes = [
        '/take-my-class',
        '/take-my-class/',
        '/take-my-class-1',
        '/take-my-class-1/',
        '/take-my-class-2',
        '/take-my-class-2/',
        '/take-my-exam',
        '/take-my-exam/',
    ];

    const shouldHideHeaderFooter = hideHeaderFooterRoutes.includes(pathname || '');

    // Routes where the header should be deferred until interaction to optimize LCP
    const deferHeaderRoutes = [
        '/take-my-class',
        '/take-my-class/',
        '/take-my-class-1',
        '/take-my-class-1/',
        '/take-my-class-2',
        '/take-my-class-2/',
        '/take-my-exam',
        '/take-my-exam/',
    ];

    const shouldDeferHeader = deferHeaderRoutes.includes(pathname || '');
    const [headerVisible, setHeaderVisible] = useState(!shouldDeferHeader);

    // Detect user interaction to load deferred header
    useEffect(() => {
        if (!shouldDeferHeader || headerVisible) return;

        const handleInteraction = () => {
            setHeaderVisible(true);
            removeEventListeners();
        };

        const removeEventListeners = () => {
            window.removeEventListener('scroll', handleInteraction);
            window.removeEventListener('mousemove', handleInteraction);
            window.removeEventListener('touchstart', handleInteraction);
            window.removeEventListener('keydown', handleInteraction);
        };

        window.addEventListener('scroll', handleInteraction, { passive: true });
        window.addEventListener('mousemove', handleInteraction, { passive: true });
        window.addEventListener('touchstart', handleInteraction, { passive: true });
        window.addEventListener('keydown', handleInteraction, { passive: true });

        return removeEventListeners;
    }, [shouldDeferHeader, headerVisible]);

    return (
        <AuthProvider>
            {headerVisible && <AppNav />}
            {children}
            {!shouldHideHeaderFooter && <Footer />}
            <WhatsApp />
            <CookieBanner />
            {/* <ExitPopUp
          open={openExitPopup}
          handleClose={() => setOpenExitPopup(false)}
        />
      </div> */}
        </AuthProvider>
    );
};

export default MainLayout;
